// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPKr92sg4mWyXKeAez1YEyYmemusGdIuU',
    appId: '1:280380268706:web:e73fb11376d613c77c37fb',
    messagingSenderId: '280380268706',
    projectId: 'still-vim-476615-t9',
    authDomain: 'still-vim-476615-t9.firebaseapp.com',
    storageBucket: 'still-vim-476615-t9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5LVHJ_R8vyhKtDeFBF3PtDiK2xXNi7dc',
    appId: '1:280380268706:android:77ed48790fb10d727c37fb',
    messagingSenderId: '280380268706',
    projectId: 'still-vim-476615-t9',
    storageBucket: 'still-vim-476615-t9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAem-r7_Qkc5uJ0Rr_TWzPhTSUdfmF-oI0',
    appId: '1:280380268706:ios:4bae6b79ea3edd7f7c37fb',
    messagingSenderId: '280380268706',
    projectId: 'still-vim-476615-t9',
    storageBucket: 'still-vim-476615-t9.firebasestorage.app',
    iosBundleId: 'com.example.managerKey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAem-r7_Qkc5uJ0Rr_TWzPhTSUdfmF-oI0',
    appId: '1:280380268706:ios:4bae6b79ea3edd7f7c37fb',
    messagingSenderId: '280380268706',
    projectId: 'still-vim-476615-t9',
    storageBucket: 'still-vim-476615-t9.firebasestorage.app',
    iosBundleId: 'com.example.managerKey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPKr92sg4mWyXKeAez1YEyYmemusGdIuU',
    appId: '1:280380268706:web:393e476d43c83bf47c37fb',
    messagingSenderId: '280380268706',
    projectId: 'still-vim-476615-t9',
    authDomain: 'still-vim-476615-t9.firebaseapp.com',
    storageBucket: 'still-vim-476615-t9.firebasestorage.app',
  );
}
